In [1]:
import numpy as np

## Numpy Stacking
- Stacking means combining multiple arrays together into a single array.

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

vertical_join = np.vstack((a,b))  # Joins arrays row-wise (top to bottom).

horizontal_join = np.hstack((a,b))  # Joins arrays column-wise (side by side).

stacked = np.stack((a,b), axis=1) # Adds a new axis while combining arrays.

a = np.array([[1,2]])
b = np.array([[3,4]])

concat = np.concatenate((a,b), axis=1)  # General method to combine arrays.


print(vertical_join)
print()
print(horizontal_join)
print()
print(stacked)
print()
print(concat)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]

[[1 4]
 [2 5]
 [3 6]]

[[1 2 3 4]]


## Numpy Splitting
- Splitting means breaking one array into smaller arrays.
- np.split() → Splits an array into multiple sub-arrays.
- np.hsplit() → Splits an array horizontally (column-wise).
- np.vsplit() → Splits an array vertically (row-wise).

In [14]:
a = np.array([1,2,3,4,5,6])

In [18]:
result = np.split(a, 3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [19]:
# Horizontal Split

a = np.array([[1,2,3,4],
              [5,6,7,8]])

print(np.hsplit(a, 2))

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [20]:
# Vertical Split

a = np.array([[1,2],
              [3,4],
              [5,6],
              [7,8]])

print(np.vsplit(a,2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


## Linear Algebra Operations

In [25]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

print("Matrix Multiplication: \n", a @ b)  # ✅ Best

print(np.dot(a, b))  # ⚠️ Older/general

print(np.matmul(a, b)) # good

Matrix Multiplication: 
 [[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [27]:
# Transpose of Matrix

a = np.array([[1,2,3],
              [4,5,6]])

print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [30]:
# Determinant of Matrix

a = np.array([[1,2],
              [3,4]])

det = np.linalg.det(a)

print(det)

-2.0000000000000004


In [31]:
# Inverse of Matrix

print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


#### Eigen Values & Eigen Vectors

-> Very important in:

- PCA
- ML
- Computer Vision

In [34]:
a = np.array([[1,2],
              [3,4]])

values, vectors = np.linalg.eig(a)

print(values)
print()
print(vectors)

[-0.37228132  5.37228132]

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
