# Mathematical Operations in NumPy

###### Date : 28/05/2026 : Thursday

## Arithmetic Operations
- Addition (`+`)
- Subtraction (`-`)
- Multiplication (`*`)
- Division (`/`)
- Modulus (`%`)
- Power (`**`)

---

## Statistical Operations
- Mean → `np.mean()`
- Median → `np.median()`
- Mode → `stats.mode()`
- Standard Deviation → `np.std()`
- Variance → `np.var()`
- Sum → `np.sum()`
- Minimum → `np.min()`
- Maximum → `np.max()`

---

## Mathematical Functions
- Square Root → `np.sqrt()`
- Absolute Value → `np.abs()`
- Exponential → `np.exp()`
- Logarithm → `np.log()`

---

## Trigonometric Functions
- Sine → `np.sin()`
- Cosine → `np.cos()`
- Tangent → `np.tan()`

---

## Matrix Operations
- Matrix Addition
- Matrix Subtraction
- Matrix Multiplication → `@` or `np.matmul()`
- Transpose → `.T`

---

## Axis-Based Operations
- Row-wise Operations → `axis=1`
- Column-wise Operations → `axis=0`

---

## Rounding Operations
- Floor → `np.floor()`
- Ceil → `np.ceil()`
- Round → `np.round()`

In [1]:
import numpy as np

In [2]:
arr  = np.array([1,2,3,4,6,7,8])

In [5]:
# Addition
print(arr + 2)

# Power
print(arr ** 2)

# Modulus
print(arr % 2)

[ 3  4  5  6  8  9 10]
[ 1  4  9 16 36 49 64]
[1 0 1 0 0 1 0]


In [7]:
# Statistical Operations

arr  = np.array([1,2,3,4,6,4,8,2])

# Mean
mean = np.mean(arr)
print(mean)

# Median
median = np.median(arr)
print(median)

3.75
3.5


In [8]:
# Sum

sum_arr = np.sum(arr)
print(sum_arr)

30


In [12]:
# Log
print("Log: ", np.log(arr) ,"\n")

# Exponential
print("Exponent: ", np.exp(arr))

Log:  [0.         0.69314718 1.09861229 1.38629436 1.79175947 1.38629436
 2.07944154 0.69314718] 

Exponent:  [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 4.03428793e+02 5.45981500e+01 2.98095799e+03 7.38905610e+00]


## Matrix Multiplication

In [15]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

print(a @ b)
print()
print(np.matmul(a, b))

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


## Rounding Operations

In [19]:
arr = np.array([1.2, 2.7, 3.5])

# Floor
print("Floor rounding: ", np.floor(arr))

# Ceil
print("Ceil rounding: ", np.ceil(arr))

# Round
print("Round: ", np.round(arr))

Floor rounding:  [1. 2. 3.]
Ceil rounding:  [2. 3. 4.]
Round:  [1. 3. 4.]


### Array Size

In [20]:
import sys

arr = np.array([1,2,3,4,5,6,7,8])

print("Size of array: ", sys.getsizeof(arr))

Size of array:  176


In [21]:
nums = [1,2,3,4,5,6,7,8]

print("Size of List: ", sys.getsizeof(nums))


Size of List:  120


In [23]:
arr = np.array([1,2,3], dtype=np.int32)

print(arr.nbytes)

12
