# NumPy - Numerical Python

### Created By:
**Jaydeep Bheda**

---

## Introduction
- NumPy is a Python library used for working with arrays.
- It is fast and memory efficient.

---

## Numpy Array Datatype
- **ndarray** → n-dimensional array

---

## Date
- 27-05-2026 : Wednesday

In [1]:
import numpy as np

In [ ]:
# Simple Array

nums = np.array([1,2,3,4,5,6,7,8])

print(nums)
print("shape: ", nums.shape)
print("datatype: ",type(nums))

[1 2 3 4 5 6 7 8]
shape:  (8,)
datatype:  <class 'numpy.ndarray'>


In [ ]:
# Range

nums = np.arange(1, 20, 2)

print(nums)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
# Multi-dimensional Zeros Array

nums = np.zeros((2,4,8))

nums

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [ ]:
nums = np.full((3, 10), 7)
nums

array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [ ]:
# SLicing in numpy array

n = [1,2,3,4,5,6,7,8]

nums = np.array(n)

print("Normal slice: ", nums[0:8])

print("Negative Slicing: ", nums[-7: -4]) # Negative slicing

print("Slice till end: ", nums[2:])

print("Slice with steps: ", nums[0:7:2])

Normal slice:  [1 2 3 4 5 6 7 8]
Negative Slicing:  [2 3 4]
Slice till end:  [3 4 5 6 7 8]
Slice with steps:  [1 3 5 7]


### Numpy Universal Function

In [ ]:
nums = np.array([4, 0.1, 3, 10, 8, 0.2])

print("Numpy Array: ", nums)

# Square root of each element
sqrt = np.sqrt(nums)
print("Square Root of array: ", sqrt)

# Exponents
expo = np.exp(nums)
print("Exponent: ", expo)

# Min / Max
min = np.min(nums)
max = np.max(nums)
print("Min: ", min, "Max: ", max)

# Trignometry - [sin , cos, log]
log = np.log(nums)
print("Logn : ", log)

sin_val = np.sin(nums)
print("Sin value: ", sin_val)

nums2 =np.array([-4, 0, 2, 9, -10])

# Sign Positive or Negative
sign_val = np.sign(nums2)
print("Sign value: ", sign_val)

# Absolute values
abs_val = np.absolute(nums2)
print("Abs values: ", abs_val)

Numpy Array:  [ 4.   0.1  3.  10.   8.   0.2]
Square Root of array:  [2.         0.31622777 1.73205081 3.16227766 2.82842712 0.4472136 ]
Exponent:  [5.45981500e+01 1.10517092e+00 2.00855369e+01 2.20264658e+04
 2.98095799e+03 1.22140276e+00]
Min:  0.1 Max:  10.0
Logn :  [ 1.38629436 -2.30258509  1.09861229  2.30258509  2.07944154 -1.60943791]
Sin value:  [-0.7568025   0.09983342  0.14112001 -0.54402111  0.98935825  0.19866933]
Sign value:  [-1  0  1  1 -1]
Abs values:  [ 4  0  2  9 10]


### Numpy Copy vs View
| Copy | View |
|---|---|
| Creates new array | Shares original array memory |
| Changes do not affect original | Changes affect original |
| Uses extra memory | Memory efficient |
| Created using `copy()` | Created using slicing/view() |

In [ ]:
nums = np.array([1,2,3,4,5])

new_np = nums.copy()

new_np[0] = 51

print("Numpy Copy")
print("Original nums: ", nums)
print("Copied nums:   ", new_np)
print()

new_np = nums.view()

new_np[0] = 51

print("Numpy Copy")
print("Original nums: ", nums)
print("View nums:     ", new_np)

Numpy Copy
Original nums:  [1 2 3 4 5]
Copied nums:    [51  2  3  4  5]

Numpy Copy
Original nums:  [51  2  3  4  5]
View nums:      [51  2  3  4  5]


### Shape and Reshape

In [ ]:
# create 1-D Numpy Array and Get Shape
nums1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("Numpy Array: ", nums1)
print("Array Shape", nums1.shape)

print()

# create 2-D Numpy Array and Get Shape
nums2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("Numpy Array: \n", nums2)
print("Array Shape", nums2.shape)

print()

# Reshape 2-D
nums3 = nums1.reshape(3,4)
print("Reshaped 2-d: \n", nums3)
print("Array Shape", nums3.shape)

print()

# Reshape 3-D
nums4 = nums1.reshape(2, 3, 2)
print("Reshaped 3-d: \n", nums4)
print("Array Shape", nums4.shape)

print()
print("'Flatten n-dimension -> 1D'")

# Flatten to 1-D
nums5 = nums4.reshape(-1)
print("Reshaped 1-d: \n", nums5)
print("Array Shape", nums5.shape)

Numpy Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Array Shape (12,)

Numpy Array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Array Shape (2, 5)

Reshaped 2-d: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array Shape (3, 4)

Reshaped 3-d: 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Array Shape (2, 3, 2)

'Flatten n-dimension -> 1D'
Reshaped 1-d: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Array Shape (12,)


### Iterating through Array

In [ ]:
# Iterating through numpy array

nums = np.array([[1,2,3,4,5], [6,7,8,9,10]])

# Method 1:

for i in nums:
  for j in i:
    print(j, end=" ")
  print()

print()

#Method 2:

for i in np.nditer(nums):
  print(i, end=" ")


1 2 3 4 5 
6 7 8 9 10 

1 2 3 4 5 6 7 8 9 10 

### Sorting Numpy Array

-  Original doesn't get change.

In [ ]:
# Numerical SOrting
nums = np.array([[8,6,3,-1],[4,3,2,6]])

print(np.sort(nums))

print()

# Alphabetical sorting
words = np.array(['jay', 'deep','dea', 'vijay', 'harshi'])
print(np.sort(words))

[[-1  3  6  8]
 [ 2  3  4  6]]

['dea' 'deep' 'harshi' 'jay' 'vijay']


### Searching Numpy Array

In [ ]:
nums = np.array([[8,6,3,-1,4],[4,3,-1,2,6]])

x = np.where(nums == -1)

print(x)

(array([0, 1]), array([3, 2]))


### Filtering Numpy Array

In [ ]:
arr = np.array([41, 42, 43, 44, 41])

x = [True, False, False, False, True] # keep value where its True, exclude where False.

newarr = arr[x]

print(newarr)

[41 41]


In [ ]:
# If Array if Huge
filtered = []

for num in arr:
  if num == 41:
    filtered.append(True)
  else:
    filtered.append(False)

print(arr[filtered])

[41 41]


In [ ]:
# Shortcut
filtered = arr == 41
print(arr)
print(filtered)
print(arr[filtered])

[41 42 43 44 41]
[ True False False False  True]
[41 41]


## Datatypes In NumPy

| Code | Datatype |
|---|---|
| `i` | Integer |
| `b` | Boolean |
| `u` | Unsigned Integer |
| `f` | Float |
| `c` | Complex Float |
| `m` | Timedelta |
| `M` | Datetime |
| `O` | Object |
| `S` | String |
| `U` | Unicode String |
| `V` | Fixed chunk of memory for other type (Void) |

In [ ]:
# Create an array with data type string
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
# Create an array with data type 4 bytes integer

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


- The **astype()** function creates a copy of the array, and allows you to specify the data type as a parameter.

In [ ]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i') # or int

print(newarr)
print(newarr.dtype)

[1 2 3]
int32
